### ISSUE TITLE
Question: single sign and unlock content of all web

### ISSUE THREAD

**Issue by michalzobec** [unverbuggt/mkdocs-encryptcontent-plugin#50]
Hello, I tryied your plugin before cca a year. It is working perfectly. But I have little problem with request for login for anyone page on web if I will use global password.

This is some argessive for users. It is possible implement single login and unlock content of all web?

Thank you very much.

**Comment by unverbuggt** [comment]
Hi,

in order to set the global password, the user needs to press **Ctrl+**ENTER after entering the correct password, at least that is the way in version 2.x of this plugin (read [here](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/tree/master#remember-password)).

However I'm working on the release of version3, so read my [reply](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/issues/51#issuecomment-1703758472) to issue51 if you're interested in testing the new release.

**Comment by michalzobec** [comment]
hello unverbuggt, thank you for your reply.

thank you but I want easy for use solution and request for *press **Ctrl+**ENTER after entering the correct password* is not easy for some users, and impossible for users with phone or tablet.

so I will wait for new version 3.0. I tried found new feature in documentation and I not found it. so you plan this feature? or what is name of this feature?

thank you very much for your work and help.

**Comment by unverbuggt** [comment]
Yes, doing that (Ctrl+Enter) is impossible for mobile users. That and other reasons led to a different implementation in v3.

But the current version also got a fallback mechanism. All you need to do is set `remember_password: true` in the plugin configuration. If you use a global password and someone enters the correct password on the homepage or the site, then this password is tried on all other pages for decryption

**Comment by michalzobec** [comment]
hello unverbuggt, thank you. it sounds great. I will wait for final version.
