### ISSUE TITLE
Strange item...  Recover Password

### ISSUE THREAD

**Issue by JamesRivers** [unverbuggt/mkdocs-encryptcontent-plugin#55]
Ok this is odd.. my mkdocs.yml file and main branch has gone and I am left with just the gh-pages branch... so I cannot view the password I set on this site via the yml. Is there a way to recover the password?

**Comment by unverbuggt** [comment]
Oh, that's bad. Hope you can recover the branches somehow (maybe try something like [this](https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git), because git normally doesn't delete anything completely, if it was checked in once).

There is absolutely no way to recover a password from a generated page. However, if the password was not very long, you might be able to brute force it. And, if you didn't encrypt the search index, then all the pages content can be found in the index somewhere.

**Comment by JamesRivers** [comment]
thanks @unverbuggt  the branches listed is only `gh-pages`
