### ISSUE TITLE
How to separately configure the prompt information

### ISSUE THREAD

**Issue by W1ndys** [unverbuggt/mkdocs-encryptcontent-plugin#67]
How to separately configure the prompt information "summary", "encryption_info_message", "placeholder", and "decryption_failure_message" for each page? I have tested it, and the result is that "encryption_info_message" can be configured separately for each page, but other variables can only Depends on global settings in mkdocs.yml

**Comment by unverbuggt** [comment]
Hi,

currently `encryption_summary` and `encryption_info_message` can be used to customize the strings per-page (see [here](https://unverbuggt.github.io/mkdocs-encryptcontent-plugin/usage/#custom-per-page-strings)). Had to rename `summary` from "mkdocs.yml" to `encryption_summary` because these meta tags might be needed for other puposes (f.ex. to be used by search engines).  
Placeholder and decryption failure message is currently not customizable per page, but they can be customized per-language.

**Comment by W1ndys** [comment]
> Hi,
> 
> currently `encryption_summary` and `encryption_info_message` can be used to customize the strings per-page (see [here](https://unverbuggt.github.io/mkdocs-encryptcontent-plugin/usage/#custom-per-page-strings)). Had to rename `summary` from "mkdocs.yml" to `encryption_summary` because these meta tags might be needed for other puposes (f.ex. to be used by search engines). Placeholder and decryption failure message is currently not customizable per page, but they can be customized per-language.

Thank you, I will read your explanation carefully
